services:
  - type: web
    name: geotagapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true 